#ifndef _USER_H
#define _USER_H
//
// Define an Interface Guid so that app can find the device and talk to it.
//
#include <initguid.h>
// {93263916-57C3-404B-B158-51EACC10C3EA}
// 第一个参数GUID_DEVINTERFACE_My_PCIe，是自定义的一个名字，就指代GUID了
DEFINE_GUID(GUID_DEVINTERFACE_My_PCIe, 
    0x93263916, 0x57c3, 0x404b, 0xb1, 0x58, 0x51, 0xea, 0xcc, 0x10, 0xc3, 0xea);
#define My_PCIe_IOCTL_IN_BUFFERED CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)//the least value is 0x800
#define My_PCIe_IOCTL_OUT_BUFFERED CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define My_PCIe_IOCTL_READ_PADDRESS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define My_PCIe_IOCTL_WRITE_OFFSETADDRESS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif